class Autogenerated {
  String? status;
  String? message;
  List<AllInventories>? allInventories;
  String? vendorPermission;
  String? isOwner;

  Autogenerated(
      {this.status,
      this.message,
      this.allInventories,
      this.vendorPermission,
      this.isOwner});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    message = json['message'];
    if (json['all_inventories'] != null) {
      allInventories = <AllInventories>[];
      json['all_inventories'].forEach((v) {
        allInventories!.add(new AllInventories.fromJson(v));
      });
    }
    vendorPermission = json['vendor_permission'];
    isOwner = json['is_owner'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['status'] = this.status;
    data['message'] = this.message;
    if (this.allInventories != null) {
      data['all_inventories'] =
          this.allInventories!.map((v) => v.toJson()).toList();
    }
    data['vendor_permission'] = this.vendorPermission;
    data['is_owner'] = this.isOwner;
    return data;
  }
}

class AllInventories {
  int? storeInventoryId;
  int? warehouseId;
  int? storeLocationId;
  int? productid;
  String? skuCode;
  String? barcode;
  int? incomingQuantity;
  int? committedQuantity;
  int? availableStock;
  int? addedby;
  int? addedfrom;
  int? postId;
  String? name;
  String? slug;
  int? producttype;
  Null? status;
  int? progressSteps;
  String? sku;
  String? image;
  String? thumbnail;
  String? smallimage;
  String? gallery1;
  String? gallery2;
  String? gallery3;
  String? gallery4;
  String? video;
  int? procatid;
  int? proBrand;
  Null? price;
  Null? saleprice;
  Null? specialprice;
  Null? startdate;
  Null? enddate;
  Null? quantity;
  Null? lowStockLimit;
  Null? trackQuantity;
  Null? sellOutOfStock;
  int? sizeChart;
  String? chartType;
  Null? description;
  String? longdescription;
  int? trending;
  String? upsellProducts;
  String? crossSellProducts;
  String? createdtime;
  String? updatedtime;
  int? vendorProductId;
  int? vendorid;
  int? vendorPrice;
  int? vendorSaleprice;
  int? vendorQuantity;
  int? vendorProductStatus;
  String? includePincodes;
  String? excludePincodes;
  String? vendorNotesForProduct;
  String? createdDate;
  String? updatedDate;
  int? vendorStoreId;
  String? locationTitle;
  String? conatctPersonName;
  String? addressline1;
  String? city;
  String? state;
  String? country;
  String? pincode;
  String? googleMapUrl;
  String? emailId;
  String? countryCode;
  String? phoneNo;
  int? storeLocationStatus;
  int? defaultStoreLocation;
  int? territoryId;
  String? pickupLocation;
  int? priceMargin;
  String? latitude;
  String? longitude;
  int? addedFrom;
  String? storeLocationCreatedtime;
  String? storeLocationUpdatedtime;
  Null? vid;
  int? pid;
  Null? variation;
  Null? varsku;
  Null? varimage;
  int? sid;
  int? freeshipping;
  int? shippingcost;
  int? weightUnit;
  String? unitType;
  int? weight;
  int? length;
  int? width;
  int? height;
  int? shippingStatus;
  int? pincodeRestrictionSettings;
  String? simpleRegularprice;
  String? simpleSaleprice;
  Null? variableRegularprice;
  Null? variableSaleprice;
  int? simpleQuantity;
  Null? variableQuantity;
  String? termIds;
  String? websiteurl;
  String? imageUrl;

  AllInventories(
      {this.storeInventoryId,
      this.warehouseId,
      this.storeLocationId,
      this.productid,
      this.skuCode,
      this.barcode,
      this.incomingQuantity,
      this.committedQuantity,
      this.availableStock,
      this.addedby,
      this.addedfrom,
      this.postId,
      this.name,
      this.slug,
      this.producttype,
      this.status,
      this.progressSteps,
      this.sku,
      this.image,
      this.thumbnail,
      this.smallimage,
      this.gallery1,
      this.gallery2,
      this.gallery3,
      this.gallery4,
      this.video,
      this.procatid,
      this.proBrand,
      this.price,
      this.saleprice,
      this.specialprice,
      this.startdate,
      this.enddate,
      this.quantity,
      this.lowStockLimit,
      this.trackQuantity,
      this.sellOutOfStock,
      this.sizeChart,
      this.chartType,
      this.description,
      this.longdescription,
      this.trending,
      this.upsellProducts,
      this.crossSellProducts,
      this.createdtime,
      this.updatedtime,
      this.vendorProductId,
      this.vendorid,
      this.vendorPrice,
      this.vendorSaleprice,
      this.vendorQuantity,
      this.vendorProductStatus,
      this.includePincodes,
      this.excludePincodes,
      this.vendorNotesForProduct,
      this.createdDate,
      this.updatedDate,
      this.vendorStoreId,
      this.locationTitle,
      this.conatctPersonName,
      this.addressline1,
      this.city,
      this.state,
      this.country,
      this.pincode,
      this.googleMapUrl,
      this.emailId,
      this.countryCode,
      this.phoneNo,
      this.storeLocationStatus,
      this.defaultStoreLocation,
      this.territoryId,
      this.pickupLocation,
      this.priceMargin,
      this.latitude,
      this.longitude,
      this.addedFrom,
      this.storeLocationCreatedtime,
      this.storeLocationUpdatedtime,
      this.vid,
      this.pid,
      this.variation,
      this.varsku,
      this.varimage,
      this.sid,
      this.freeshipping,
      this.shippingcost,
      this.weightUnit,
      this.unitType,
      this.weight,
      this.length,
      this.width,
      this.height,
      this.shippingStatus,
      this.pincodeRestrictionSettings,
      this.simpleRegularprice,
      this.simpleSaleprice,
      this.variableRegularprice,
      this.variableSaleprice,
      this.simpleQuantity,
      this.variableQuantity,
      this.termIds,
      this.websiteurl,
      this.imageUrl});

  AllInventories.fromJson(Map<String, dynamic> json) {
    storeInventoryId = json['store_inventory_id'];
    warehouseId = json['warehouse_id'];
    storeLocationId = json['store_location_id'];
    productid = json['productid'];
    skuCode = json['sku_code'];
    barcode = json['barcode'];
    incomingQuantity = json['incoming_quantity'];
    committedQuantity = json['committed_quantity'];
    availableStock = json['available_stock'];
    addedby = json['addedby'];
    addedfrom = json['addedfrom'];
    postId = json['post_id'];
    name = json['name'];
    slug = json['slug'];
    producttype = json['producttype'];
    status = json['status'];
    progressSteps = json['progress_steps'];
    sku = json['sku'];
    image = json['image'];
    thumbnail = json['thumbnail'];
    smallimage = json['smallimage'];
    gallery1 = json['gallery1'];
    gallery2 = json['gallery2'];
    gallery3 = json['gallery3'];
    gallery4 = json['gallery4'];
    video = json['video'];
    procatid = json['procatid'];
    proBrand = json['pro_brand'];
    price = json['price'];
    saleprice = json['saleprice'];
    specialprice = json['specialprice'];
    startdate = json['startdate'];
    enddate = json['enddate'];
    quantity = json['quantity'];
    lowStockLimit = json['low_stock_limit'];
    trackQuantity = json['track_quantity'];
    sellOutOfStock = json['sell_out_of_stock'];
    sizeChart = json['size_chart'];
    chartType = json['chart_type'];
    description = json['description'];
    longdescription = json['longdescription'];
    trending = json['trending'];
    upsellProducts = json['upsell_products'];
    crossSellProducts = json['cross_sell_products'];
    createdtime = json['createdtime'];
    updatedtime = json['updatedtime'];
    vendorProductId = json['vendor_product_id'];
    vendorid = json['vendorid'];
    vendorPrice = json['vendor_price'];
    vendorSaleprice = json['vendor_saleprice'];
    vendorQuantity = json['vendor_quantity'];
    vendorProductStatus = json['vendor_product_status'];
    includePincodes = json['include_pincodes'];
    excludePincodes = json['exclude_pincodes'];
    vendorNotesForProduct = json['vendor_notes_for_product'];
    createdDate = json['created_date'];
    updatedDate = json['updated_date'];
    vendorStoreId = json['vendor_store_id'];
    locationTitle = json['location_title'];
    conatctPersonName = json['conatct_person_name'];
    addressline1 = json['addressline1'];
    city = json['city'];
    state = json['state'];
    country = json['country'];
    pincode = json['pincode'];
    googleMapUrl = json['google_map_url'];
    emailId = json['email_id'];
    countryCode = json['country_code'];
    phoneNo = json['phone_no'];
    storeLocationStatus = json['store_location_status'];
    defaultStoreLocation = json['default_store_location'];
    territoryId = json['territory_id'];
    pickupLocation = json['pickup_location'];
    priceMargin = json['price_margin'];
    latitude = json['latitude'];
    longitude = json['longitude'];
    addedFrom = json['added_from'];
    storeLocationCreatedtime = json['store_location_createdtime'];
    storeLocationUpdatedtime = json['store_location_updatedtime'];
    vid = json['vid'];
    pid = json['pid'];
    variation = json['variation'];
    varsku = json['varsku'];
    varimage = json['varimage'];
    sid = json['sid'];
    freeshipping = json['freeshipping'];
    shippingcost = json['shippingcost'];
    weightUnit = json['weight_unit'];
    unitType = json['unit_type'];
    weight = json['weight'];
    length = json['length'];
    width = json['width'];
    height = json['height'];
    shippingStatus = json['shipping_status'];
    pincodeRestrictionSettings = json['pincode_restriction_settings'];
    simpleRegularprice = json['simple_regularprice'];
    simpleSaleprice = json['simple_saleprice'];
    variableRegularprice = json['variable_regularprice'];
    variableSaleprice = json['variable_saleprice'];
    simpleQuantity = json['simple_quantity'];
    variableQuantity = json['variable_quantity'];
    termIds = json['term_ids'];
    websiteurl = json['websiteurl'];
    imageUrl = json['image_url'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['store_inventory_id'] = this.storeInventoryId;
    data['warehouse_id'] = this.warehouseId;
    data['store_location_id'] = this.storeLocationId;
    data['productid'] = this.productid;
    data['sku_code'] = this.skuCode;
    data['barcode'] = this.barcode;
    data['incoming_quantity'] = this.incomingQuantity;
    data['committed_quantity'] = this.committedQuantity;
    data['available_stock'] = this.availableStock;
    data['addedby'] = this.addedby;
    data['addedfrom'] = this.addedfrom;
    data['post_id'] = this.postId;
    data['name'] = this.name;
    data['slug'] = this.slug;
    data['producttype'] = this.producttype;
    data['status'] = this.status;
    data['progress_steps'] = this.progressSteps;
    data['sku'] = this.sku;
    data['image'] = this.image;
    data['thumbnail'] = this.thumbnail;
    data['smallimage'] = this.smallimage;
    data['gallery1'] = this.gallery1;
    data['gallery2'] = this.gallery2;
    data['gallery3'] = this.gallery3;
    data['gallery4'] = this.gallery4;
    data['video'] = this.video;
    data['procatid'] = this.procatid;
    data['pro_brand'] = this.proBrand;
    data['price'] = this.price;
    data['saleprice'] = this.saleprice;
    data['specialprice'] = this.specialprice;
    data['startdate'] = this.startdate;
    data['enddate'] = this.enddate;
    data['quantity'] = this.quantity;
    data['low_stock_limit'] = this.lowStockLimit;
    data['track_quantity'] = this.trackQuantity;
    data['sell_out_of_stock'] = this.sellOutOfStock;
    data['size_chart'] = this.sizeChart;
    data['chart_type'] = this.chartType;
    data['description'] = this.description;
    data['longdescription'] = this.longdescription;
    data['trending'] = this.trending;
    data['upsell_products'] = this.upsellProducts;
    data['cross_sell_products'] = this.crossSellProducts;
    data['createdtime'] = this.createdtime;
    data['updatedtime'] = this.updatedtime;
    data['vendor_product_id'] = this.vendorProductId;
    data['vendorid'] = this.vendorid;
    data['vendor_price'] = this.vendorPrice;
    data['vendor_saleprice'] = this.vendorSaleprice;
    data['vendor_quantity'] = this.vendorQuantity;
    data['vendor_product_status'] = this.vendorProductStatus;
    data['include_pincodes'] = this.includePincodes;
    data['exclude_pincodes'] = this.excludePincodes;
    data['vendor_notes_for_product'] = this.vendorNotesForProduct;
    data['created_date'] = this.createdDate;
    data['updated_date'] = this.updatedDate;
    data['vendor_store_id'] = this.vendorStoreId;
    data['location_title'] = this.locationTitle;
    data['conatct_person_name'] = this.conatctPersonName;
    data['addressline1'] = this.addressline1;
    data['city'] = this.city;
    data['state'] = this.state;
    data['country'] = this.country;
    data['pincode'] = this.pincode;
    data['google_map_url'] = this.googleMapUrl;
    data['email_id'] = this.emailId;
    data['country_code'] = this.countryCode;
    data['phone_no'] = this.phoneNo;
    data['store_location_status'] = this.storeLocationStatus;
    data['default_store_location'] = this.defaultStoreLocation;
    data['territory_id'] = this.territoryId;
    data['pickup_location'] = this.pickupLocation;
    data['price_margin'] = this.priceMargin;
    data['latitude'] = this.latitude;
    data['longitude'] = this.longitude;
    data['added_from'] = this.addedFrom;
    data['store_location_createdtime'] = this.storeLocationCreatedtime;
    data['store_location_updatedtime'] = this.storeLocationUpdatedtime;
    data['vid'] = this.vid;
    data['pid'] = this.pid;
    data['variation'] = this.variation;
    data['varsku'] = this.varsku;
    data['varimage'] = this.varimage;
    data['sid'] = this.sid;
    data['freeshipping'] = this.freeshipping;
    data['shippingcost'] = this.shippingcost;
    data['weight_unit'] = this.weightUnit;
    data['unit_type'] = this.unitType;
    data['weight'] = this.weight;
    data['length'] = this.length;
    data['width'] = this.width;
    data['height'] = this.height;
    data['shipping_status'] = this.shippingStatus;
    data['pincode_restriction_settings'] = this.pincodeRestrictionSettings;
    data['simple_regularprice'] = this.simpleRegularprice;
    data['simple_saleprice'] = this.simpleSaleprice;
    data['variable_regularprice'] = this.variableRegularprice;
    data['variable_saleprice'] = this.variableSaleprice;
    data['simple_quantity'] = this.simpleQuantity;
    data['variable_quantity'] = this.variableQuantity;
    data['term_ids'] = this.termIds;
    data['websiteurl'] = this.websiteurl;
    data['image_url'] = this.imageUrl;
    return data;
  }
}
